[misc]
assume_yes = true
disable = ["yarn", "pnpm", "flatpak", "git_repos", "nix"]
pre_sudo = true
skip_notify = true

[linux]
arch_package_manager = "paru"

[firmware]
upgrade = true

[commands]
{{#if dotter.packages.desktop}}"VSCode Insiders" = "paru -S code-insiders-bin --rebuild --noconfirm"{{/if}}
