[misc]
assume_yes = true
disable = ["yarn", "pnpm", "flatpak", "git_repos"]
pre_sudo = true
skip_notify = true

[linux]
show_arch_news = false
arch_package_manager = "paru"

[firmware]
upgrade = true

[commands]
{{#if dotter.packages.desktop}}"VSCode Insiders" = "paru -S code-insiders-bin --noconfirm"
"HyprStatus" = "paru -Qi hyprland hyprpaper hyprcursor hypridle hyprlock hyprpicker hyprlang xdg-desktop-portal-hyprland"{{/if}}
