[misc]
assume_yes = true
disable = ["yarn", "pnpm", "flatpak"]
pre_sudo = true
cleanup = true
skip_notify = true

[linux]
arch_package_manager = "paru"

[commands]
{{#if dotter.packages.desktop}}"VSCode Insiders" = "paru -S visual-studio-code-insiders-bin --rebuild"{{/if}}
