name: Feature Request
description: File a feature request
title: "[FEATURE] <title>"
labels: ["type: feature", "needs triage"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you're requesting.
      options:
        - label: I have searched for an existing issues
          required: true

  - type: textarea
    attributes:
      label: Problem
      description: A concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution
      description: A concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: A concise description of any alternative solutions or features you've considered.
    validations:
      required: true
