[default.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/zshenv" = "~/.zshenv"
"rtx.toml" = "~/.config/rtx/config.toml"
"topgrade.toml" = "~/.config/topgrade.toml"

[desktop]
depends = ["default"]

[desktop.files]
"wallpaper.jpg" = { target = "~/Pictures/wallpaper.jpg", type = "symbolic" }

[hypr]
depends = ["desktop"]

[hypr.files]
eww = "~/.config/eww"
rofi = "~/.config/rofi"
"hypr" = "~/.config/hypr"
"bin/udf.sh" = "~/.bin/update-desktop-files.sh"
"external/flight" = { target = "~/Desktop/flight-themes", type = "symbolic" }
"pacman/udf.hook" = { target = "/usr/share/libalpm/hooks/update-desktop-files.hook", type = "template", owner = "root" }
