[default.files]
bin = "~/.bin"
"zsh/zshrc" = "~/.zshrc"
"zsh/zshenv" = "~/.zshenv"
"rtx.toml" = "~/.config/rtx/config.toml"

[desktop]
depends = ["default"]

[desktop.files]
eww = "~/.config/eww"
hypr = "~/.config/hypr"
rofi = "~/.config/rofi"
"wallpaper.jpg" = "~/Pictures/wallpaper.jpg"
"pacman/udf.hook" = { target = "/usr/share/libalpm/hooks/update-desktop-files.hook", type = "template", owner = "root" }
