[default.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/zshenv" = "~/.zshenv"
"mise.toml" = "~/.config/mise/config.toml"
"topgrade.toml" = "~/.config/topgrade.toml"

[desktop]
depends = ["default"]

[desktop.files]
"wallpaper.jpg" = { target = "~/Pictures/wallpaper.jpg", type = "symbolic" }
"logid.cfg" = { target = "/etc/logid.cfg", type = "symbolic", owner = "root" }

[hypr]
depends = ["desktop"]

[hypr.files]
rofi = "~/.config/rofi"
hypr = "~/.config/hypr"
"bin/audio.sh" = "~/.bin/audio.sh"
dunstrc = "~/.config/dunst/dunstrc"
"bin/udf.sh" = "~/.bin/update-desktop-files.sh"
eww = { target = "~/.config/eww", type = "symbolic", recurse = false }
"external/flight" = { target = "~/Desktop/flight-themes", type = "symbolic" }
"pacman/udf.hook" = { target = "/usr/share/libalpm/hooks/update-desktop-files.hook", type = "template", owner = "root" }
